spring:
  application:
    name: container-booking-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/container_booking
  security:
    user:
      name: user@maersk.com
      password: password@maersk.com


server:
  port: 8080

external:
  api:
    base-url: https://maersk.com/api/bookings
  retry:
    max-attempts: 3

database:
  retry:
    max-attempts: 3

logging:
  level:
    root: INFO